---

- name: Configure VM
  hosts: all
  become: true
  vars:
    app_dir: /opt/app
    db: "{{ lookup('env', 'DB') }}"
    psql_user: "{{ lookup('env', 'PSQL_USER') }}"
    psql_pwd: "{{ lookup('env', 'PSQL_PWD') }}"
    kc_user: "{{ lookup('env', 'KC_USER') }}"
    kc_pwd: "{{ lookup('env', 'KC_PWD') }}"
    kc_client_secret: "{{ lookup('env', 'KC_CLIENT_SECRET') }}"
  vars_files:
    - secret.var.yaml
  roles:
    - install
    - deploy
